package com.salihyusufcankurt.issuemanagement.entity;

import com.fasterxml.jackson.databind.ser.Serializers;
import lombok.*;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "issue")
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode

public class Issue extends Serializers.Base {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "description", length = 1000)
    private String description;

    @Column(name = "details", length = 4000)
    private String details;

    @Column(name = "date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date date;

    @Column(name = "issue_status")
    @Enumerated(EnumType.STRING)
    private IssueStatus issueStatus;

    @JoinColumn(name = "assignee_user_id")
    @ManyToOne(optional = true, fetch = FetchType.LAZY)
    private User assignee;

    @JoinColumn(name = "project_id")
    @ManyToOne(optional = true, fetch = FetchType.LAZY)
    private Project project;

    // Bu class orm de bir tabloya karşılık geleceği için başına @Entity anotasyonu koyduk.

    // @Id : primary key belirtmek için koyduk.

    // Bu iki anotasyon olmazsa olmaz table anotasyonlarıdır.

    // @Table : tablonun bilgileri için kullanılır.

    // @GeneratedValue  : autogenerated veri oluşturmak için kullanılır.

    // @Enumerated(EnumType.STRING) : enum verinin veritabanında nasıl tutlacağını belirtmek için kullanılır.
    // ordinary enum sınıfındaki sırasına göre 0 1 2 3 gibi tutar, string ise olduğu gibi ismiyle tutar.

    // @Data  : getter ve setter metodlarının gizli şekilde oluşturulmasını ve böylece kodun sade kalmasını sağlar.

    // @NoArgsConstructor : Bu sınıfın boş bir constructor metodunu yaratır.

    // @AllArgsConstructor : Tüm parametreleri almış bir constructor metodu yaratır.

    // @ToString : Bu sınıfın toString metodunu otomatik override eder

    // @EqualsAndHashCode : Equals ve HasCode metodlarını override eder.

    // @ManyToOne : Bu sınıf için birçok issue bir tane user ile ilişlikendirilebilir demektir.







}
